gpu           : 0
dataset       : "kvae"

# network setting
dim_inputs    : 8
dim_outputs   : 8
N_ensemble    : 5
units         : '512, 512, 512'

# optimizer setting
epoch         : 100
batch_size    : 128
learning_rate : 0.001
reload_model  : ''
log_dir       : 'logs'