gpu           : 0
dataset       : "sin"

# network setting
dim_input     : 1
dim_output    : 1
N_ensemble    : 5
units         : '512, 512, 512'

# optimizer setting
epoch         : 50
batch_size    : 64
learning_rate : 0.001
reload_model  : 'M5_20220216000350'
log_dir       : 'logs'