gpu           : 0
dataset       : "sin"

# network setting
dim_input     : 1
dim_output    : 1
N_ensemble    : 5
units         : '512, 512, 512'

# optimizer setting
optimizer     : "adam"
epoch         : 30
batch_size    : 64
learning_rate : 0.001

loss          : "smooth_L1"

reload_model  : 'M5_20220216142109'
log_dir       : 'logs'