gpu           : 0
kvae_model    : "dclaw_64x64_N2001_seq25_dim_a8_Epoch5000_seed0_SCREW_task_space_3DoF_20210902190800_random_nonfix_to_canonical_kvae"
# dataset       : "/hdd_mount/logs/dclaw_64x64_N151_seq20_dim_a8_Epoch10000_seed1_SCREW_NO_RANDOMIZE_20210813185936_canonical_to_canonical_kvae/models/Epochs_9999/dataset.npz"
dataset       : "/hdd_mount/data_npz/dclaw/64x64/SCREW_task_space_3DoF_for_ensemble/dclaw_64x64_N1801_seq25.npz"

# network setting
dim_inputs    : 14
dim_outputs   : 8
N_ensemble    : 5
units         : '512, 512, 512'
# units         : '128, 128, 128, 128, 128'
# units         : '64, 128, 64'

# optimizer setting
epoch         : 2000
batch_size    : 64
learning_rate : 0.001
reload_model  : ''
log_dir       : 'logs'