gpu           : 0
dataset       : "cos2D"

# network setting
dim_input     : 2
dim_output    : 1
N_ensemble    : 5
units         : '512, 512, 512, 512'
# units         : '200, 200, 200, 200'

# optimizer setting
optimizer     : "adam"
epoch         : 100
batch_size    : 128
learning_rate : 0.001

loss          : "smooth_L1"

reload_model  : 'M5_20220216224452'
log_dir       : 'logs'